from selenium.webdriver.common.by import By


class SettingsPageLocators:
    loc_profile = (By.XPATH, '//*[@id="top-head"]/div/div[2]/span')
    loc_choose_gender = (By.ID, 'gender')
    loc_gender_male = (By.XPATH, '//*[@value="1"]')
    loc_gender_female = (By.XPATH, '//*[@value="2"]')
    loc_save_button = (By.XPATH, '//*[@name="submit"]')
    loc_settings = (By.XPATH, '//*[@href="https://rezka.ag/settings/"]')
    loc_selected_male_gender = (By.XPATH, '//*[@value="1"][@selected="selected"]')
    loc_selected_female_gender = (By.XPATH, '//*[@value="2"][@selected="selected"]')
    loc_current_email = (By.XPATH, '//*[@value="lovitopor68@gmail.com"]')
    loc_changed_email = (By.XPATH, '//*[@value="lovitopor68@example.com"]')
    loc_security_tab = (By.XPATH, '//*[@href="/settings/security/"]')
    loc_current_pass = (By.ID, 'altpass')
    loc_new_pass = (By.ID, 'password1')
    loc_repeat_pass = (By.ID, 'password2')
    loc_promo_tab = (By.XPATH, '//*[@href = "/settings/promotion/"]')
    loc_continue_btn = (By.XPATH, '//*[@colspan="2"]//*[@href="/payments/"]')
    loc_yes_btn = (By.XPATH, '//*[@value="Да"]')
    loc_1mont_sub = (By.XPATH, '//*[@for="pl-item-30"]')
    loc_yes_payment_btn = (By.ID, 'pay-button-proccess-yes')
    loc_go_to_payment_btn = (By.ID, 'pay-button-proccess')
    loc_monobank_api = (By.XPATH, '//*[@src="https://api.streampay.org/api/assets/payment_methods/privatbank.png"]')
    loc_confirm_bank = (By.ID, 'set-method')
    loc_accept_terms = (By.ID, 'accept-terms')
    loc_made_payment = (By.ID, 'made-payment')
    loc_yes_final_btn = (By.XPATH, '//*[@class="custom-radio-label f-inter-400 text-20 text-gray-dark"]')
    loc_confirm_payment = (By.ID, 'confirm-payment')
    loc_no_receipt_btn = (
        By.XPATH, '//div[@class="custom-radio-label f-inter-400 text-20 text-gray-dark has-receipt-label"]')
    loc_loader_after_payment = (By.XPATH, '//*[@class="loader mx-auto"]')
    loc_payment_history = (By.XPATH, '//*[@href="/payments/history/"]')
    loc_last_tansaction = (By.XPATH, '//*[@id="main"]//tr[1]/td[1]')
    loc_name_payer = (By.XPATH, '//input[@type="text"]')
    last_transaction_sum_locator = (By.XPATH, '//*[@id="main"]//*[contains(text(), "100")]')
